apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: rajcharan2002/frontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "200m"
          volumeMounts:                           # Add volume mount for config map
            - name: config-volume
              mountPath: /etc/config
      affinity:                                   # Add the node affinity section here
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-group                  # Specify the node group label key
                    operator: In
                    values:
                      - frontback                    # Specify the node group label value
      volumes:                                    # Define the volume for config map
        - name: config-volume
          configMap:
            name: nginx-config                    # Name of the ConfigMap to mount
            items:
              - key: BACKEND_SERVICE_NAME         # Specify the key from the ConfigMap
                path: backend_service.env         # Specify the path in the container
