apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: rajcharan2002/frontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "200m"
      affinity:                         # Add the node affinity section here
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-group          # Specify the node group label key
                    operator: In
                    values:
                      - frontback            # Specify the node group label value
