apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_ENGINE: django.db.backends.mysql
  DB_NAME: chatapp
  DB_USER: chatapp
  DB_HOST: database
  DB_PORT: "3306"  # Enclose the numeric value in double quotes
